API:
  api_base_url: https://api.discogs.com
  convertion_ratio: = 20
  format: = "application/vnd.discogs.v2.plaintext+json"
  headers:
    Accept: application/vnd.discogs.v2.plaintext+json
    Content-Type: application/json
    User-Agent: Dump Library/1.1 +https://github.com/blackbunt/dump-discogs-collection-2-csv
  https_base_url: = https://www.discogs.com/
  limit: = 100
  params:
    page: 1
    per_page: 1
  processing_url: https://api.discogs.com/users/{username}/collection/folders/0/releases?page={page}&per_page={per_page}&token={token}
  release_url: https://api.discogs.com/users/{username}/collection/folders/0/releases
  scrape:
    per_page: 10
  value_url: https://api.discogs.com/users/{username}/collection/value
Login:
  apitoken: 
  username: 
